### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by cabol** [SafeBoda/throttlex#6]
## General Items

- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [x] It's tested
- [x] It has 100% coverage
- [x] It has dialyzer
- [x] Add CI (Issue #3)

## Features for the First Version

- [ ] Implement throttle function (Issue #4)
- [ ] Add the possibility to manage custom limit conditions different than just a max rate, like percentage, etc. (Issue #5)

## Exhibition

- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description

## Examples

- [ ] It provides a sample application
- [ ] Examples of use are documented in the README or linked from there
- [ ] Simple benchmarks

## Publish

- [ ] It's published on [Hex.pm](https://hex.pm)
